import { supabase } from './supabase-client.js';

// Submit registration to Supabase
export async function submitStatisticsRegistration(formData) {
    try {
        const registrationData = {
            student_name: formData.get('student_name'),
            student_phone: formData.get('student_phone'),
            parent_phone: formData.get('parent_phone'),
            school_type: formData.get('school_type'),
            attendance_type: formData.get('attendance_type'),
            username: null,  // Will be generated by the trigger
            password: null   // Will be generated by the trigger
        };

        // Check for existing registration
        const { exists, error: checkError } = await checkExistingRegistration(registrationData.student_phone);
        if (checkError) {
            console.error('Error checking existing registration:', checkError);
            throw checkError;
        }
        if (exists) {
            return { 
                success: false, 
                error: 'هذا الطالب مسجل بالفعل',
                errorCode: 'DUPLICATE_STUDENT'
            };
        }

        // Get Supabase client
        const supabaseClient = await supabase();
        
        // Log the registration attempt
        console.log('Attempting to register student:', {
            ...registrationData,
            student_phone: '****' + registrationData.student_phone.slice(-4),
            parent_phone: '****' + registrationData.parent_phone.slice(-4)
        });

        // Register the student
        const { data, error } = await supabaseClient
            .from('stats_review_2025')
            .insert([registrationData])
            .select()
            .single();

        if (error) {
            console.error('Registration error:', error);
            
            // Handle specific error cases
            if (error.code === '23505' || (error.message && error.message.includes('duplicate key value'))) {
                return { 
                    success: false, 
                    error: 'هذا الطالب مسجل بالفعل',
                    errorCode: '23505'
                };
            }
            
            if (error.code === '42501') {
                return {
                    success: false,
                    error: 'عذراً، لا يمكن إتمام التسجيل حالياً. يرجى المحاولة لاحقاً.',
                    errorCode: '42501'
                };
            }
            
            throw error;
        }

        // Log successful registration
        console.log('Registration successful:', {
            username: data.username,
            student_phone: '****' + data.student_phone.slice(-4)
        });

        return { success: true, data };
    } catch (error) {
        console.error('Error submitting registration:', error);
        
        return { 
            success: false, 
            error: error.message || 'حدث خطأ أثناء التسجيل. يرجى المحاولة مرة أخرى.',
            errorCode: error.code || 'UNKNOWN_ERROR'
        };
    }
}

// Check if student is already registered
async function checkExistingRegistration(studentPhone) {
    try {
        const supabaseClient = await supabase();
        
        console.log('Checking existing registration for:', '****' + studentPhone.slice(-4));
        
        const { data, error } = await supabaseClient
            .from('stats_review_2025')
            .select('id')
            .eq('student_phone', studentPhone)
            .maybeSingle();

        if (error) {
            console.error('Error checking registration:', error);
            throw error;
        }

        return { exists: !!data, error: null };
    } catch (error) {
        console.error('Error checking existing registration:', error);
        return { exists: false, error };
    }
} 