import { supabase } from './supabase-client.js';

// Maximum number of retries for transient errors
const MAX_RETRIES = 3;
const RETRY_DELAY = 1000; // 1 second

// Helper function to delay execution
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

// Submit registration to Supabase
export async function submitStatisticsRegistration(formData) {
    try {
        const registrationData = {
            student_name: formData.get('student_name'),
            student_phone: formData.get('student_phone'),
            parent_phone: formData.get('parent_phone'),
            school_type: formData.get('school_type'),
            attendance_type: formData.get('attendance_type'),
            username: null,  // Will be generated by the trigger
            password: null   // Will be generated by the trigger
        };

        // Validate input data
        if (!registrationData.student_name || !registrationData.student_phone || 
            !registrationData.parent_phone || !registrationData.school_type || 
            !registrationData.attendance_type) {
            throw new Error('جميع الحقول مطلوبة');
        }

        // Check for existing registration
        const { exists, error: checkError } = await checkExistingRegistration(registrationData.student_phone);
        if (checkError) {
            console.error('Error checking existing registration:', checkError);
            throw checkError;
        }
        if (exists) {
            return { 
                success: false, 
                error: 'هذا الطالب مسجل بالفعل',
                errorCode: 'DUPLICATE_STUDENT'
            };
        }

        // Get Supabase client
        const supabaseClient = await supabase();
        
        // Log the registration attempt
        console.log('Attempting to register student:', {
            ...registrationData,
            student_phone: '****' + registrationData.student_phone.slice(-4),
            parent_phone: '****' + registrationData.parent_phone.slice(-4)
        });

        // Register the student
        const { data, error } = await supabaseClient
            .from('stats_review_2025')
            .insert([registrationData])
            .select('*');

        if (error) {
            console.error('Registration error:', error);
            
            // Handle specific error cases
            if (error.code === '23505' || (error.message && error.message.includes('duplicate key value'))) {
                return { 
                    success: false, 
                    error: 'هذا الطالب مسجل بالفعل',
                    errorCode: '23505'
                };
            }
            
            if (error.code === '42501') {
                return {
                    success: false,
                    error: 'عذراً، لا يمكن إتمام التسجيل حالياً. يرجى المحاولة لاحقاً.',
                    errorCode: '42501'
                };
            }
            
            throw error;
        }

        // Get the first record since we know we only inserted one
        const registeredStudent = data[0];

        // Log successful registration
        console.log('Registration successful:', {
            student_phone: '****' + registrationData.student_phone.slice(-4)
        });

        // Return success with registration data including generated credentials
        return { 
            success: true, 
            data: {
                ...registeredStudent,
                studentName: registeredStudent.student_name,
                studentPhone: registeredStudent.student_phone,
                parentPhone: registeredStudent.parent_phone,
                schoolType: registeredStudent.school_type === 'azhar' ? 'الثانوي الازهري' : 'الثانوي العامة (ادبي)',
                attendanceType: registeredStudent.attendance_type === 'zoom' ? 'اونلاين' : 'حضوري',
                username: registeredStudent.username,
                password: registeredStudent.password
            }
        };
    } catch (error) {
        console.error('Error submitting registration:', error);
        
        return { 
            success: false, 
            error: error.message || 'حدث خطأ أثناء التسجيل. يرجى المحاولة مرة أخرى.',
            errorCode: error.code || 'UNKNOWN_ERROR'
        };
    }
}

// Check if student is already registered
async function checkExistingRegistration(studentPhone) {
    try {
        const supabaseClient = await supabase();
        
        console.log('Checking existing registration for:', '****' + studentPhone.slice(-4));
        
        const { data, error } = await supabaseClient
            .from('stats_review_2025')
            .select('id')
            .eq('student_phone', studentPhone)
            .limit(1);

        if (error) {
            console.error('Error checking registration:', error);
            throw error;
        }

        return { exists: data && data.length > 0, error: null };
    } catch (error) {
        console.error('Error checking existing registration:', error);
        return { exists: false, error };
    }
} 